# max_chain_links: 3
# Max number of recursions per circuit, you shouldn't ever really need to change this
# -
# autosave_interval_minutes: 30
# Autosave time in minutes
# -
# max_delay_time: 10
# Max allowed delay for one recevier in seconds (QuantumConnectors.ignoreLimits will overwrite this)
# -
# max_receivers_per_circuit: 20
# Max receivers for a single circuit (QuantumConnectors.ignoreLimits will overwrite this)
#-
# verbose-logging: false
# If true the plugin will log details related to saving files/etc.
#
max_chain_links: 3
autosave_interval_minutes: 30
max_delay_time: 10
max_receivers_per_circuit: 20
verbose_logging: false