name: QuantumConnectors
main: com.ne0nx3r0.quantum.QuantumConnectors
version: '2.0.3'
database: false
startup: postworld
description: Wireless redstone connections
commands:
   qc:
      description: Create a quantum connector